#!/bin/bash

# Set variables
artist=`cat ./data/artist`
album=`cat ./data/album`
title=`cat ./data/title`
language=`langid < zzlyrics000.lrc`

# Move lyrics files to Music directory
mv zzlyrics000.lrc ./Music/"$artist"/"$album"/"${title} - orig.lrc"
mv zzlyrics002.lrc ./Music/"$artist"/"$album"/"${title}.lrc" #translated version

# check if not translated, if so remove extra lrc
if [[ $language != *"zh"* && $language != *"ja"* && $language != *"ko"* && $language != *"ru"* ]]; then
	mv "./Music/$artist/$album/${title} - orig.lrc" "./Music/$artist/$album/${title}.lrc"
fi

# Remove unnecessary files
rm -f gmon.out
rm -f .gitignore
rm -f ./*.txt
rm -f -r ./downloads
rm -f zzlyrics000.lrc
rm -f zzlyrics001.lrc

# this files are generated when an error occur (no name)
mp3="./Music/"$artist"/"$album"/.mp3"
rm -f "$mp3"
lrc="./Music/"$artist"/"$album"/.lrc"
rm -f "$lrc"
orig="./Music/"$artist"/"$album"/ - orig.lrc"
rm -f "$orig"

# Check if error exist in lyrics file, if it does delete it
if grep -q "No such file or directory" ./Music/"$artist"/"$album"/"${title}.lrc"; then
	rm -f ./Music/"$artist"/"$album"/"${title}.lrc"
fi

clear