#!/bin/bash

token="YourMusixmatchTokenHere"

# Remove all files in the ./data/lyrics/ directory
rm -f ./data/lyrics/*

artist=`cat ./data/artist`
title=`cat ./data/title`

# mxlrc.py query format is:("artist, title")
# to avoid error removes comma for Artist/Title), i.e Artist(s) = a, b, c becomes Artist(s) = a  b  c
artist2="${artist//,}"
title2="${title//,}"

# Create a query file with the artist(s) and song title
# it's important that query is read from a file rather than directly calling it with mxlrc.py,
# spaces will give undesirable results (treat search as different songs when query is directly fed to mxlrc.py compare to using a file)
echo "$artist2, $title2" > ./data/query
python3 ./data/mxlrc.py --song ./data/query --token $token
mv ./lyrics/*.lrc ./zzlyrics000.lrc
rm -f -r ./lyrics

# to ensure synched type of lyrics is the one that is saved, check for timestanp
# line 7 is just arbritary number most probably timestamp for lyrics can be found here
# in some case song length is included in the lyric file which have a timestamp format,
# this is the reason a specific line(7th) is being search to avoid reading timestamp from duration
sed -n '7,7p' ./zzlyrics000.lrc > ./data/time
time="[0-5][0-9]:[0-5][0-9]\.[0-9]"

# check if timestamp is present delete file if not found
if grep -q "$time" ./data/time; then
:
else
	rm -f ./zzlyrics000.lrc
fi