#!/bin/sh

syrics -u
wait
mv ./downloads/*.lrc ./zzlyrics000.lrc

sed -n '7,7p' ./zzlyrics000.lrc > ./data/time
time="[0-5][0-9]:[0-5][0-9]\.[0-9]"

if grep -q "$time" ./data/time; then
:
else 
	rm -f ./zzlyrics000.lrc 
fi