#!/bin/bash

# converts Korean characters to Romaja
./data/ko2romaja
language=`langid < zzlyrics001.lrc`

# Detect the language of the lyrics using the langid library and save the result in the "language" file
# simplified Chinese and Japanese shared some character, it's important to distinguish between the two
# ZH
# If the language is detected as Chinese, convert Chinese characters to Pinyin
if [[ $language =~ zh ]]; then
	script -c ./data/zh2pinyin --force zzlyrics002.lrc
	# some cleanups
	sed -i 's/ ]/]/g' zzlyrics002.lrc
	sed -i 's/] /]/g' zzlyrics002.lrc
	sed -i 's/\([0-9]\) : /\1:/g' zzlyrics002.lrc
	sed -i '1d;$d' zzlyrics002.lrc
	sed -i 's/ \[/[/g' zzlyrics002.lrc
	sed -i 's/\[ /[/g' zzlyrics002.lrc
	sed -i 's/\r//g' zzlyrics002.lrc;
	
else
	# JA
	# If the language is detected as Japanese, convert Japanese characters to Romaji
	if [[ $language =~ ja ]]; then
		script -c ./data/ja2romaji --force zzlyrics002.lrc
		# some cleanups
		sed -i 's/ ]/]/g' zzlyrics002.lrc
		sed -i 's/] /]/g' zzlyrics002.lrc
		sed -i 's/( /(/g' zzlyrics002.lrc
		sed -i 's/ )/)/g' zzlyrics002.lrc
		sed -i 's/: /:/g' zzlyrics002.lrc
		sed -i 's/ :/:/g' zzlyrics002.lrc
		sed -i 's/\. \([0-9]\)/.\1/g' zzlyrics002.lrc
		sed -i 's/ - /-/g' zzlyrics002.lrc
		sed -i 's/ ??/]♪/g' zzlyrics002.lrc
		sed -i '1d' zzlyrics002.lrc
		sed -i '$d' zzlyrics002.lrc
		sed -i '$d' zzlyrics002.lrc
		sed -i "s/' /'/g" zzlyrics002.lrc
		
	else mv ./zzlyrics001.lrc ./zzlyrics002.lrc
	fi
fi

# RU
# If the language is detected as Russian, convert Crylic characters to Latin
if [[ $language =~ ru ]]; then
	cyrtranslit -l RU -i zzlyrics001.lrc -o zzlyrics002.lrc
	
else mv ./zzlyrics001.lrc ./zzlyrics002.lrc
fi