#!/bin/sh

# This script reads lines from the zzlyrics001.lrc file and passes each line to the 'pinyin-tool' command
# if not done line by line, it outputs whole content in one line
# The 'pinyin-tool' command converts the Chinese characters to pinyin

while read line; do 
	echo $line; 
done < zzlyrics001.lrc | pinyin-tool